AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template for CloudTrail checking lambdas and step
  function harness
Parameters:
  CloudTrailBucketName:
    Description: The name of the s3 bucket storage location that receives CloudTrail
      events.
    Type: String
  SplunkHttpEventCollectorToken:
    Description: HEC token from the Splunk server which will receive updates on the
      status of the action as it completes. (format - 12345678-qwer-asdf-zxcv-123456789qwe)
    Type: String
  SplunkHttpEventCollectorURL:
    Description: The HEC endpoint server and port (default 8088) of the the Splunk
      environment which will receive updates on the status of the action as it completes.
      (format - server:port)
    Type: String
Resources:
  LambdaFunctionCTMonitoring:
    DependsOn:
    - LambdaFunctionCTMonitoringRole
    Properties:
      CodeUri: s3://nstone-snap-bucket2/b4ff04776a46b8f6a74ec9d03b291c37
      Description: Uses the Firehose PUT API to push CloudTrail events to a Firehose
        that delivers to Splunk
      Environment:
        Variables:
          firehose_stream_name: cloudtrail-monitoring
      FunctionName: cloudtrail-monitoring
      Handler: cloudtrail-monitoring.lambda_handler
      Role:
        Fn::GetAtt:
        - LambdaFunctionCTMonitoringRole
        - Arn
      Runtime: python2.7
      Timeout: 90
    Type: AWS::Serverless::Function
  LambdaFunctionCTMonitoringRole:
    DependsOn:
    - s3bucket
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Effect: Allow
            Resource:
            - arn:aws:logs:*:*:*
          - Action:
            - s3:getObject
            - s3:putObject
            - s3:ListBucket
            Effect: Allow
            Resource:
              Fn::Join:
              - ''
              - - 'arn:aws:s3:::'
                - Ref: CloudTrailBucketName
          - Action:
            - firehose:PutRecord
            Effect: Allow
            Resource:
            - arn:aws:firehose:*:*:*
          Version: '2012-10-17'
        PolicyName: LambdaFirehosePutPolicy
    Type: AWS::IAM::Role
  s3bucket:
    Properties:
      VersioningConfiguration:
        Status: Enabled
    Type: AWS::S3::Bucket
